export const GALLERY_ALBUMS = [
  {
    id: 'landscapes',
    tags: ['landscape'],
    excludeTags: ['travel', 'seascape', 'seasonal'],
    highlightedPicture: '2020-10-17_0213.jpg'
  },
  {
    id: 'seascapes',
    tags: ['seascape'],
    excludeTags: ['landscape'],
    highlightedPicture: '2021-12-04_0135.jpg'
  },
  {
    id: 'astro',
    tags: ['moon', 'sun'],
    excludeTags: ['landscape', 'seascape', 'travel'],
    highlightedPicture: '2018-11-24_0178.jpg'
  },
  {
    id: 'portraits',
    tags: ['portrait'],
    highlightedPicture: '2017-06-11_0014.jpg'
  },
  {
    id: 'travel',
    tags: ['travel'],
    highlightedPicture: '2021-10-27_0280.jpg'
  },
  {
    id: 'seasonal',
    tags: ['seasonal'],
    highlightedPicture: '2022-11-13_0023.jpg'
  },
  {
    id: 'night',
    tags: ['night photography'],
    highlightedPicture: '2022-06-25_0028.jpg'
  }
]

export const SORTING_OPTIONS = [
  'info-group',
  'date',
  'name',
  'shot-info-group',
  'shot-info.shutter-speed',
  'shot-info.aperture',
  'shot-info.iso',
  'shot-info.focal-length'
]
export const DEFAULT_SORTING_OPTION = 'date'
export const DISABLED_SORTING_OPTIONS = ['info-group', 'shot-info-group']
export const PENDING_EVAL_SORTING_OPTIONS = ['shot-info.shutter-speed']

export const ALLOWED_PICTURE_TAGS = [
  'alacant',
  'arctic',
  'aurora borealis',
  'autumn',
  'b&w',
  'barcelona',
  'beach',
  'blue hour',
  'bridge',
  'castle',
  'catalunya',
  'cave',
  'chapel',
  'city',
  'clear',
  'cloudy',
  'coast',
  'cold',
  'comunitat valenciana',
  'costa blanca',
  'costa brava',
  'costa daurada',
  'dark',
  'dawn',
  'day light',
  "delta de l'ebre",
  'drama',
  'dusk',
  'family',
  'fjord',
  'flowers',
  'forest',
  'france',
  'full moon',
  'golden hour',
  'haze',
  'hiking',
  'hills',
  'human',
  'ice',
  'iceland',
  'italy',
  'lake',
  'lavender',
  'leaves',
  'light pollution',
  'lighthouse',
  'lofoten islands',
  'long exposure',
  'love',
  'mediterranean',
  'milky way',
  'minimal',
  'mood',
  'moon',
  'mountain',
  'nature',
  'night',
  'norway',
  'panorama',
  'park',
  'path',
  'portrait',
  'provence',
  'rain',
  'reflections',
  'river',
  'rocks',
  'rural',
  'salt lake',
  'sea',
  'skyline',
  'sport',
  'spring',
  'star trail',
  'summer',
  'sunrise',
  'sunset',
  'sunstar',
  'supermoon',
  'telephoto',
  'textures',
  'tower',
  'travel',
  'trees',
  'valley',
  'warm',
  'water flow',
  'waterfall',
  'waves',
  'wind',
  'winter',
  'woods'
]
